#配置数据源
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/cloud?useUnicode=true&characterEncoding=utf8
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    pool:
     max-active: 8
     min-idle: 0
     max-idle: 8
     max-wait: 10000
  database: 2
# Tomcat配置
server:
    context-path: /
    port: 8088
#    address: 127.0.0.1 只能本地访问  address:192.168.199.163 可以内网访问

#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  


